/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Product, ShippingPort, ShippingRoute, Shipment, Language } from './types';

// Helper to resolve asset paths with correct BASE_URL for GitHub Pages support
const resolveAsset = (path: string) => {
  const cleanPath = path.startsWith('/') ? path.slice(1) : path;
  return `${import.meta.env.BASE_URL}${cleanPath}`;
};

// Import newly updated image assets
const cashewImg = resolveAsset('/assets/images/Cashew.jpg');
const pistachioImg = resolveAsset('/assets/images/Pistachio.jpg');
const broccoliImg = resolveAsset('/assets/images/Broccli.jpg');
const tomatoImg = resolveAsset('/assets/images/tomato.jpg');
const onionImg = resolveAsset('/assets/images/seatruck_agro_harvest.jpg');
const drumstickImg = resolveAsset('/assets/images/seatruck_agro_harvest.jpg');

export const HERO_BANNER_IMG = resolveAsset('/assets/images/seatruck_fruit_hero_banner_1784107067767.jpg');
export const AGRO_HARVEST_IMG = resolveAsset('/assets/images/seatruck_agro_harvest.jpg');

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    nav_home: 'Home',
    nav_portfolio: 'Products',
    nav_logistics: 'Logistics Map',
    nav_tracking: 'Live Tracking',
    nav_contact: 'Inquire Now',
    tagline: 'Connecting Global Markets from Dubai',
    hero_title: 'Global Agro Import Export Excellence',
    hero_subtitle: 'SEATRUCK NEXUSBRIDGE GENERAL TRADING - FZCO delivers high-grade agro commodities and industrial raw materials worldwide from our Global Headquarters in Dubai, United Arab Emirates.',
    cta_explore: 'View Commodities',
    cta_track: 'Track Live Cargo',
    section_portfolio_title: 'Our Agro Commodities',
    section_portfolio_subtitle: 'Premium agricultural goods processed, packed, and exported under strict global compliance.',
    all_categories: 'All Categories',
    cat_grains: 'Grains & Pulses',
    cat_spices: 'Spices & Seasonings',
    cat_dry_fruits: 'Dry Fruits & Nuts',
    cat_fresh_produce: 'Fresh Fruits & Vegetables',
    search_placeholder: 'Search commodities...',
    specs_origin: 'Premium Origin',
    specs_packing: 'Standard Packaging',
    specs_moq: 'Minimum Order (MOQ)',
    specs_grade: 'Export Grade',
    specs_loading: 'Loading Capacity',
    inquiry_btn: 'Send Product Inquiry',
    close: 'Close',
    technical_specs: 'Technical Specifications',
    shipping_details: 'Shipping & Vessel Specs',
    copied_msg: 'Details copied to inquiry form!',
    section_logistics_title: 'Interactive Global Shipping Routes',
    section_logistics_subtitle: 'Hover on routing paths to analyze active voyages carrying agricultural cargo from primary supply centers.',
    route_details: 'Route Analysis',
    transit_time: 'Transit Duration',
    primary_cargo: 'Primary Commodities',
    vessel_on_duty: 'Vessel On-Duty',
    active_now: 'Active Voyage',
    ports_connected: 'Hubs Connected',
    section_tracking_title: 'Real-Time Cold Chain Tracking',
    section_tracking_subtitle: 'Monitor reefer container vitals, marine routing progression, and live moisture levels in real-time.',
    enter_tracking_num: 'Enter Tracking ID or Bill of Lading',
    custom_simulator_title: 'Simulate Custom Shipment',
    sim_commodity: 'Select Cargo',
    sim_origin: 'Origin Port',
    sim_dest: 'Destination Port',
    sim_container: 'Container Type',
    sim_vessel: 'Vessel Name',
    sim_btn: 'Launch Tracker Simulator',
    track_btn: 'Fetch Live Status',
    invalid_tracking: 'Shipment ID not found. Try ST-9283-IND or create a custom simulation below!',
    temp_hum_status: 'Reefer Telemetry & Vitals',
    container_temp: 'Container Temp',
    container_humidity: 'Relative Humidity',
    status_label: 'Current Status',
    origin_port_col: 'Dispatch Port',
    dest_port_col: 'Destination Port',
    est_delivery: 'Estimated Discharge Date',
    milestones_timeline: 'Freight Timeline Milestones',
    milestone_processing: 'Order Consolidating',
    milestone_customs: 'Export Customs Clearance',
    milestone_loaded: 'Ocean Carrier Loading',
    milestone_transit: 'In-Transit (Ocean Cargo)',
    milestone_discharging: 'Port Discharging',
    milestone_delivered: 'Delivered to Consignee',
    section_contact_title: 'Secure Commercial Inquiry',
    section_contact_subtitle: 'Establish trusted global trade channels. Reach out to our desk for clearance, pricing, and bulk scheduling.',
    form_name: 'Full Name',
    form_email: 'Professional Email',
    form_company: 'Company/Organization',
    form_country: 'Destination Country',
    form_subject: 'Inquiry Subject',
    form_message: 'Detailed Requirement Specification',
    form_product_label: 'Associated Product Range',
    form_tracking_label: 'Voyage Tracking Code (Optional)',
    form_submit: 'Transmit Trade Inquiry',
    form_sending: 'Transmitting Trade Dossier...',
    form_success_title: 'Inquiry Lodged Successfully!',
    form_success_desc: 'Your commercial requirements have been securely logged. A regional trade desk manager will respond within 6 hours.',
    inbox_title: 'Local Outbox Transmissions',
    inbox_no_records: 'No trade files transmitted in this session yet.',
    footer_text: '© 2026 SEATRUCK NEXUSBRIDGE GENERAL TRADING - FZCO. Global HQ: Dubai Silicon Oasis, Dubai, UAE. All rights reserved.',
    footer_tag: 'Seam-free cold-chain agricultural supply lines connecting continents.'
  },
  es: {
    nav_home: 'Inicio',
    nav_portfolio: 'Productos',
    nav_logistics: 'Mapa Logístico',
    nav_tracking: 'Seguimiento',
    nav_contact: 'Consultar',
    tagline: 'Conectando Mercados Globales desde Dubái',
    hero_title: 'Excelencia Global en Importación y Exportación Agroalimentaria',
    hero_subtitle: 'SEATRUCK NEXUSBRIDGE GENERAL TRADING - FZCO distribuye productos agrícolas de primera calidad y materias primas industriales en todo el mundo desde nuestra sede central en Dubái, Emiratos Árabes Unidos.',
    cta_explore: 'Ver Productos',
    cta_track: 'Seguimiento en Vivo',
    section_portfolio_title: 'Nuestros Productos Agrícolas',
    section_portfolio_subtitle: 'Productos agrícolas premium procesados, envasados y exportados bajo estrictas normas de cumplimiento internacional.',
    all_categories: 'Todas las Categorías',
    cat_grains: 'Granos y Legumbres',
    cat_spices: 'Especias y Condimentos',
    cat_dry_fruits: 'Frutos Secos y Nueces',
    cat_fresh_produce: 'Frutas y Verduras Frescas',
    search_placeholder: 'Buscar productos...',
    specs_origin: 'Origen Premium',
    specs_packing: 'Embalaje Estándar',
    specs_moq: 'Pedido Mínimo (MOQ)',
    specs_grade: 'Grado de Exportación',
    specs_loading: 'Capacidad de Carga',
    inquiry_btn: 'Enviar Consulta',
    close: 'Cerrar',
    technical_specs: 'Especificaciones Técnicas',
    shipping_details: 'Detalles de Envío y Buque',
    copied_msg: '¡Detalles copiados al formulario de consulta!',
    section_logistics_title: 'Rutas de Envío Globales Interactivas',
    section_logistics_subtitle: 'Pase el cursor sobre las rutas para analizar los viajes activos que transportan carga agrícola desde los centros de suministro.',
    route_details: 'Análisis de Ruta',
    transit_time: 'Duración del Tránsito',
    primary_cargo: 'Productos Principales',
    vessel_on_duty: 'Buque de Turno',
    active_now: 'Viaje Activo',
    ports_connected: 'Puertos Conectados',
    section_tracking_title: 'Seguimiento de Cadena de Frío en Tiempo Real',
    section_tracking_subtitle: 'Monitoree los parámetros clave del contenedor refrigerado, la progresión de la ruta marítima y la humedad en tiempo real.',
    enter_tracking_num: 'Ingrese ID de Seguimiento o Conocimiento de Embarque',
    custom_simulator_title: 'Simular Envío Personalizado',
    sim_commodity: 'Seleccionar Carga',
    sim_origin: 'Puerto de Origen',
    sim_dest: 'Puerto de Destino',
    sim_container: 'Tipo de Contenedor',
    sim_vessel: 'Nombre del Buque',
    sim_btn: 'Iniciar Simulador de Seguimiento',
    track_btn: 'Obtener Estado en Vivo',
    invalid_tracking: 'ID de envío no encontrado. Intente con ST-9283-IND o configure una simulación.',
    temp_hum_status: 'Telemetría y Estado de Refrigeración',
    container_temp: 'Temp. del Contenedor',
    container_humidity: 'Humedad Relativa',
    status_label: 'Estado Actual',
    origin_port_col: 'Puerto de Carga',
    dest_port_col: 'Puerto de Descarga',
    est_delivery: 'Fecha de Descarga Estimada',
    milestones_timeline: 'Línea de Tiempo Logística',
    milestone_processing: 'Consolidación de Carga',
    milestone_customs: 'Despacho Aduanero de Exportación',
    milestone_loaded: 'Carga en el Buque',
    milestone_transit: 'En Tránsito Marítimo',
    milestone_discharging: 'Descarga en Puerto',
    milestone_delivered: 'Entregado al Consignatario',
    section_contact_title: 'Consulta Comercial Segura',
    section_contact_subtitle: 'Establezca canales comerciales globales de confianza. Comuníquese con nuestro equipo para despacho, precios y planificación.',
    form_name: 'Nombre Completo',
    form_email: 'Correo Electrónico Profesional',
    form_company: 'Empresa / Organización',
    form_country: 'País de Destino',
    form_subject: 'Asunto de la Consulta',
    form_message: 'Especificación Detallada del Requerimiento',
    form_product_label: 'Gama de Productos Asociados',
    form_tracking_label: 'Código de Seguimiento del Viaje (Opcional)',
    form_submit: 'Transmitir Consulta Comercial',
    form_sending: 'Transmitiendo Expediente Comercial...',
    form_success_title: '¡Consulta Registrada con Éxito!',
    form_success_desc: 'Sus requisitos comerciales han sido registrados de forma segura. Un gerente comercial regional responderá en 6 horas.',
    inbox_title: 'Transmisiones en la Bandeja de Salida Local',
    inbox_no_records: 'Aún no se han transmitido archivos comerciales en esta sesión.',
    footer_text: '© 2026 SEATRUCK NEXUSBRIDGE GENERAL TRADING - FZCO. Sede Central: Dubái, EAU. Todos los derechos reservados.',
    footer_tag: 'Líneas de suministro agrícola en cadena de frío sin interrupciones que conectan continentes.'
  },
  hi: {
    nav_home: 'होम',
    nav_portfolio: 'उत्पाद श्रेणी',
    nav_logistics: 'लॉजिस्टिक्स रूट',
    nav_tracking: 'लाइव ट्रैकिंग',
    nav_contact: 'पूछताछ करें',
    tagline: 'दुबई से वैश्विक बाजारों को जोड़ना',
    hero_title: 'कृषि उत्पाद आयात-निर्यात में वैश्विक उत्कृष्टता',
    hero_subtitle: 'SEATRUCK NEXUSBRIDGE GENERAL TRADING - FZCO दुबई, संयुक्त अरब अमीरात में हमारे वैश्विक मुख्यालय से दुनिया भर में उच्च-ग्रेड कृषि जिंसों और औद्योगिक कच्चे माल की आपूर्ति करता है।',
    cta_explore: 'कृषि उत्पाद देखें',
    cta_track: 'लाइव शिपमेंट ट्रैक करें',
    section_portfolio_title: 'हमारे कृषि उत्पाद',
    section_portfolio_subtitle: 'कड़े वैश्विक मानदंडों के तहत संसाधित, पैक और निर्यात किए जाने वाले प्रीमियम कृषि उत्पाद।',
    all_categories: 'सभी श्रेणियां',
    cat_grains: 'अनाज और दालें',
    cat_spices: 'मसाले और सीजनिंग',
    cat_dry_fruits: 'सूखे मेवे और नट्स',
    cat_fresh_produce: 'ताजे फल और सब्जियां',
    search_placeholder: 'कृषि उत्पाद खोजें...',
    specs_origin: 'प्रीमियम उत्पत्ति',
    specs_packing: 'मानक पैकेजिंग',
    specs_moq: 'न्यूनतम ऑर्डर मात्रा (MOQ)',
    specs_grade: 'निर्यात ग्रेड',
    specs_loading: 'लोडिंग क्षमता',
    inquiry_btn: 'उत्पाद पूछताछ भेजें',
    close: 'बंद करें',
    technical_specs: 'तकनीकी विनिर्देश',
    shipping_details: 'शिपिंग और पोत विवरण',
    copied_msg: 'विवरण पूछताछ फ़ॉर्म में कॉपी किया गया!',
    section_logistics_title: 'इंटरैक्टिव वैश्विक शिपिंग रूट्स',
    section_logistics_subtitle: 'प्राथमिक आपूर्ति केंद्रों से कृषि कार्गो ले जाने वाले सक्रिय समुद्री यात्राओं का विश्लेषण करने के लिए रूट्स पर माउस ले जाएं।',
    route_details: 'मार्ग विश्लेषण',
    transit_time: 'पारगमन अवधि',
    primary_cargo: 'मुख्य कृषि जिंस',
    vessel_on_duty: 'ड्यूटी पर तैनात पोत',
    active_now: 'सक्रिय समुद्री यात्रा',
    ports_connected: 'कनेक्टेड पोर्ट्स',
    section_tracking_title: 'रीयल-टाइम कोल्ड चेन ट्रैकिंग',
    section_tracking_subtitle: 'रीफर कंटेनर के तापमान, पारगमन प्रगति और लाइव आर्द्रता की वास्तविक समय में निगरानी करें।',
    enter_tracking_num: 'ट्रैकिंग आईडी या बिल ऑफ लेडिंग दर्ज करें',
    custom_simulator_title: 'कस्टम शिपमेंट सिमुलेशन',
    sim_commodity: 'कार्गो चुनें',
    sim_origin: 'लोडिंग पोर्ट',
    sim_dest: 'डिस्चार्ज पोर्ट',
    sim_container: 'कंटेनर का प्रकार',
    sim_vessel: 'पोत का नाम',
    sim_btn: 'ट्रैकर सिम्युलेटर शुरू करें',
    track_btn: 'लाइव स्थिति प्राप्त करें',
    invalid_tracking: 'शिपमेंट आईडी नहीं मिली। ST-9283-IND आज़माएं या नीचे एक कस्टम सिमुलेशन बनाएं!',
    temp_hum_status: 'रीफर टेलीमेट्री और महत्वपूर्ण डेटा',
    container_temp: 'कंटेनर तापमान',
    container_humidity: 'सापेक्ष आर्द्रता',
    status_label: 'वर्तमान स्थिति',
    origin_port_col: 'लोडिंग पोर्ट',
    dest_port_col: 'डिस्चार्ज पोर्ट',
    est_delivery: 'अनुमानित डिस्चार्ज तिथि',
    milestones_timeline: 'लॉजिस्टिक्स मील के पत्थर समयरेखा',
    milestone_processing: 'ऑर्डर एकीकरण',
    milestone_customs: 'निर्यात सीमा शुल्क निकासी',
    milestone_loaded: 'समुद्री जहाज पर लोडिंग',
    milestone_transit: 'समुद्री पारगमन में',
    milestone_discharging: 'बंदरगाह पर उतरना',
    milestone_delivered: 'सफलतापूर्वक सुपुर्द',
    section_contact_title: 'सुरक्षित व्यापार पूछताछ',
    section_contact_subtitle: 'वैश्विक व्यापार चैनल स्थापित करें। हमारे व्यापार विशेषज्ञों से संपर्क करें।',
    form_name: 'पूरा नाम',
    form_email: 'पेशेवर ईमेल',
    form_company: 'कंपनी / संगठन',
    form_country: 'गंतव्य देश',
    form_subject: 'पूछताछ का विषय',
    form_message: 'विस्तृत आवश्यकता विवरण',
    form_product_label: 'संबद्ध उत्पाद श्रृंखला',
    form_tracking_label: 'शिपमेंट ट्रैकिंग कोड (वैकल्पिक)',
    form_submit: 'व्यापार पूछताछ जमा करें',
    form_sending: 'व्यापार डोजियर भेज रहा है...',
    form_success_title: 'पूछताछ सफलतापूर्वक भेजी गई!',
    form_success_desc: 'आपकी व्यापार पूछताछ सुरक्षित रूप से दर्ज कर ली गई है। 6 घंटे के भीतर आपसे संपर्क किया जाएगा।',
    inbox_title: 'स्थानीय आउटबॉक्स प्रसारण',
    inbox_no_records: 'इस सत्र में अभी तक कोई व्यापार फ़ाइल प्रसारित नहीं हुई है।',
    footer_text: '© 2026 SEATRUCK NEXUSBRIDGE GENERAL TRADING - FZCO. वैश्विक मुख्यालय: दुबई, यूएई। सर्वाधिकार सुरक्षित।',
    footer_tag: 'शीत-श्रृंखला कृषि आपूर्ति श्रृंखला बिना किसी व्यवधान के महाद्वीपों को जोड़ती है।'
  },
  ar: {
    nav_home: 'الرئيسية',
    nav_portfolio: 'المنتجات',
    nav_logistics: 'مسارات الشحن',
    nav_tracking: 'التتبع الحي',
    nav_contact: 'اتصل بنا',
    tagline: 'ربط الأسواق العالمية من دبي',
    hero_title: 'الريادة العالمية في استيراد وتصدير المنتجات الزراعية',
    hero_subtitle: 'تقوم شركة SEATRUCK NEXUSBRIDGE GENERAL TRADING - FZCO بتوريد السلع الزراعية والمواد الخام الصناعية عالية الجودة في جميع أنحاء العالم من مقرنا الرئيسي العالمي في دبي، الإمارات العربية المتحدة.',
    cta_explore: 'استكشاف السلع',
    cta_track: 'تتبع الشحنات حياً',
    section_portfolio_title: 'سلعنا الزراعية الممتازة',
    section_portfolio_subtitle: 'سلع زراعية ممتازة تتم معالجتها وتعبئتها وتصديرها بموجب معايير الامتثال العالمية الصارمة.',
    all_categories: 'جميع الفئات',
    cat_grains: 'الحبوب والبقوليات',
    cat_spices: 'التوابل والبهارات',
    cat_dry_fruits: 'الفواكه المجففة والمكسرات',
    cat_fresh_produce: 'الفواكه والخضروات الطازجة',
    search_placeholder: 'البحث عن السلع...',
    specs_origin: 'منشأ ممتاز',
    specs_packing: 'التعبئة القياسية',
    specs_moq: 'الحد الأدنى للطلب (MOQ)',
    specs_grade: 'درجة التصدير',
    specs_loading: 'سعة التحميل',
    inquiry_btn: 'إرسال استفسار',
    close: 'إغلاق',
    technical_specs: 'المواصفات الفنية',
    shipping_details: 'تفاصيل الشحن والسفينة',
    copied_msg: 'تم نسخ التفاصيل إلى نموذج الاستفسار!',
    section_logistics_title: 'مسارات الشحن العالمية التفاعلية',
    section_logistics_subtitle: 'قم بتمرير المؤشر فوق مسارات الشحن لتحليل الرحلات النشطة التي تنقل الشحنات الزراعية.',
    route_details: 'تحليل المسار',
    transit_time: 'مدة العبور',
    primary_cargo: 'السلع الأساسية',
    vessel_on_duty: 'السفينة المكلفة',
    active_now: 'رحلة نشطة',
    ports_connected: 'الموانئ المتصلة',
    section_tracking_title: 'تتبع سلسلة التبريد في الوقت الفعلي',
    section_tracking_subtitle: 'مراقبة حيوية الحاويات المبردة، تقدم الشحن البحري ومستويات الرطوبة في الوقت الفعلي.',
    enter_tracking_num: 'أدخل معرف التتبع أو بوليصة الشحن',
    custom_simulator_title: 'محاكاة شحنة مخصصة',
    sim_commodity: 'اختر الشحنة',
    sim_origin: 'ميناء الشحن',
    sim_dest: 'ميناء التفريغ',
    sim_container: 'نوع الحاوية',
    sim_vessel: 'اسم السفينة',
    sim_btn: 'بدء محاكاة التتبع',
    track_btn: 'جلب الحالة الحية',
    invalid_tracking: 'لم يتم العثور على معرف الشحنة. جرب ST-9283-IND أو قم بتكوين محاكاة مخصصة.',
    temp_hum_status: 'بيانات وتليمتري الحاوية المبردة',
    container_temp: 'درجة حرارة الحاوية',
    container_humidity: 'الرطوبة النسبية',
    status_label: 'الحالة الحالية',
    origin_port_col: 'ميناء التحميل',
    dest_port_col: 'ميناء التفريغ',
    est_delivery: 'التاريخ المتوقع للتفريغ',
    milestones_timeline: 'الجدول الزمني لمحطات الشحن',
    milestone_processing: 'تجميع الشحنة وترتيبها',
    milestone_customs: 'التخليص الجمركي للتصدير',
    milestone_loaded: 'شحن البضاعة على السفينة',
    milestone_transit: 'في العبور البحري',
    milestone_discharging: 'التفريغ في الميناء',
    milestone_delivered: 'تم التسليم للمستلم النهائي',
    section_contact_title: 'استفسار تجاري آمن',
    section_contact_subtitle: 'إنشاء قنوات تجارية عالمية موثوقة. اتصل بمكتبنا للتخليص والتسعير والجدولة الكمية.',
    form_name: 'الاسم الكامل',
    form_email: 'البريد الإلكتروني المهني',
    form_company: 'الشركة / المؤسسة',
    form_country: 'بلد الوجهة',
    form_subject: 'موضوع الاستفسار',
    form_message: 'مواصفات المتطلبات التفصيلية',
    form_product_label: 'نطاق المنتجات ذات الصلة',
    form_tracking_label: 'رمز تتبع الشحنة (اختياري)',
    form_submit: 'إرسال الاستفسار التجاري',
    form_sending: 'جاري إرسال الملف التجاري...',
    form_success_title: 'تم تسجيل الاستفسار بنجاح!',
    form_success_desc: 'لقد تم تسجيل متطلباتكم التجارية بأمان. سيرد مدير المكتب التجاري الإقليمي في غضون 6 ساعات.',
    inbox_title: 'صندوق الصادر المحلي للمراسلات',
    inbox_no_records: 'لم يتم إرسال أي ملفات تجارية في هذه الجلسة بعد.',
    footer_text: '© 2026 SEATRUCK NEXUSBRIDGE GENERAL TRADING - FZCO. المقر الرئيسي العالمي: دبي، الإمارات العربية المتحدة. جميع الحقوق محفوظة.',
    footer_tag: 'سلاسل إمداد زراعية مبردة خالية من الانقطاع تربط القارات.'
  },
  zh: {
    nav_home: '首页',
    nav_portfolio: '大宗商品',
    nav_logistics: '物流航线',
    nav_tracking: '实时追踪',
    nav_contact: '即刻咨询',
    tagline: '从迪拜连接全球市场',
    hero_title: '全球农产品进出口卓越领航者',
    hero_subtitle: 'SEATRUCK NEXUSBRIDGE GENERAL TRADING - FZCO 致力于从阿联酋迪拜的全球总部向世界各地交付优质农产品和工业原材料。',
    cta_explore: '浏览大宗商品',
    cta_track: '实时追踪货物',
    section_portfolio_title: '我们的特色农作物',
    section_portfolio_subtitle: '符合国际出口检疫标准的优质农产品。',
    all_categories: '全部类别',
    cat_grains: '谷物与豆类',
    cat_spices: '香料与调味品',
    cat_dry_fruits: '干果与坚果',
    cat_fresh_produce: '生鲜水果与蔬菜',
    search_placeholder: '搜索农产品...',
    specs_origin: '原产地',
    specs_packing: '包装规格',
    specs_moq: '最小起订量 (MOQ)',
    specs_grade: '出口等级',
    specs_loading: '装载量',
    inquiry_btn: '发送询盘',
    close: '关闭',
    technical_specs: '技术规格',
    shipping_details: '运输详情',
    copied_msg: '产品详情已复制！',
    section_logistics_title: '互动全球航运航线',
    section_logistics_subtitle: '悬停在航线上分析从主要供应中心运送农作物货物的活跃航程。',
    route_details: '航线分析',
    transit_time: '运输时效',
    primary_cargo: '主要大宗商品',
    vessel_on_duty: '执勤货轮',
    active_now: '活跃航程',
    ports_connected: '连接港口',
    section_tracking_title: '冷链实时追踪',
    section_tracking_subtitle: '实时监控冷藏集装箱的关键数据、航线进度和实时湿度。',
    enter_tracking_num: '输入追踪ID或提单号',
    custom_simulator_title: '模拟自定义货运',
    sim_commodity: '选择货物',
    sim_origin: '起运港',
    sim_dest: '目的港',
    sim_container: '集装箱类型',
    sim_vessel: '货轮名称',
    sim_btn: '启动追踪模拟器',
    track_btn: '获取实时状态',
    invalid_tracking: '未找到货运ID。请尝试 ST-9283-IND 或在下方创建自定义模拟！',
    temp_hum_status: '冷箱遥测与关键数据',
    container_temp: '集装箱温度',
    container_humidity: '相对湿度',
    status_label: '当前状态',
    origin_port_col: '起运港',
    dest_port_col: '目的港',
    est_delivery: '预计卸货日期',
    milestones_timeline: '货运里程碑时间线',
    milestone_processing: '订单整合中',
    milestone_customs: '出口海关申报',
    milestone_loaded: '装载至货轮',
    milestone_transit: '海上运输中 (Ocean Cargo)',
    milestone_discharging: '卸货港交付',
    milestone_delivered: '收货人签收完成',
    section_contact_title: '安全商业询盘',
    section_contact_subtitle: '建立互信的全球贸易渠道。联系我们的贸易专家，获取通关、定价和大宗计划。',
    form_name: '完整姓名',
    form_email: '专业邮箱',
    form_company: '公司 / 机构',
    form_country: '目的国家/地区',
    form_subject: '询盘主题',
    form_message: '详细需求规格',
    form_product_label: '相关产品范围',
    form_tracking_label: '货运追踪代码 (可选)',
    form_submit: '提交商业询盘',
    form_sending: '正在传输询盘档案...',
    form_success_title: '询盘发送成功！',
    form_success_desc: '您的商业询盘已成功记录在我们的数据库中。询盘专员将在 6 小时内联系贵公司，并提供定制报价。',
    inbox_title: '本地发件箱记录',
    inbox_no_records: '此会话中尚未发送任何询盘。',
    footer_text: '© 2026 SEATRUCK NEXUSBRIDGE GENERAL TRADING - FZCO. 全球总部：迪拜硅谷绿洲迪拜数字公园A1栋。保留所有权利。',
    footer_tag: '连接各大洲的冷链农产品供应链，确保零中断。'
  }
};
export const PRODUCTS: Product[] = [
  {
    id: 'cashews',
    category: 'dry_fruits',
    name: { en: 'Cashew Nuts', es: 'Anacardos', ar: 'كاجو', hi: 'काजू', zh: '腰果' },
    description: { en: 'Premium white raw cashew nuts (Grade W240), dense and crunchy.', es: 'Anacardos premium de color marfil súper crujientes calibre W240.', ar: 'كاجو أبيض كامل طازج ذو طعم كريمي ممتاز.', hi: 'सख्त मानकों के तहत छांटे गए मलाईदार W240 काजू।', zh: '象牙白大粒脱皮、整粒微熟的香口腰果，自然回甘。' },
    image: cashewImg,
    details: {
      en: { origin: 'Goa, India', packaging: '10kg Vacuum Tins', moq: '10 MT', grade: 'W240 White Whole', loadingCapacity: '15 MT per 20ft' },
      es: { origin: 'Goa, India', packaging: 'Latas de vacío de 10kg', moq: '10 MT', grade: 'W240 Blanco Entero', loadingCapacity: '15 MT por 20 pies' },
      ar: { origin: 'غوا، الهند', packaging: 'صفائح مفرغة ١٠ كجم', moq: '١٠ طن', grade: 'W240 أبيض كامل', loadingCapacity: '١٥ طن لكل ٢٠ قدم' },
      hi: { origin: 'गोवा, भारत', packaging: '१० किग्रा टिन वैक्यूम पाउच', moq: '१० मीट्रिक टन', grade: 'सफेद पूर्ण W240', loadingCapacity: '१५ मीट्रिक टन प्रति २० फीट' },
      zh: { origin: '果阿邦, 印度', packaging: '10公斤真空铁箱包装', moq: '10公吨', grade: 'W240 全形乳白完整', loadingCapacity: '15公吨每20尺集装箱' }
    },
    specifications: {
      en: ['Cashews/lb: 220-240 pcs', 'Color: Ivory White', 'Broken cashews: < 2%'],
      es: ['Piezas/lb: 220-240 pzs', 'Color: Marfil', 'Mermas/Rotas: < 2%'],
      ar: ['العدد/رطل: ٢٢٠-٢٤٠ حبة', 'اللون: عاجي ناصع', 'الكسر الكلي: تحت ٢٪'],
      hi: ['काजू प्रति पाउंड: २२०-२४० पीस', 'रंग: आइवरी व्हाइट', 'खण्डित टुकड़े: २% से कम'],
      zh: ['每磅颗数：220至240粒', '色泽：柔白象牙色', '碎腰果比例：少于2%']
    }
  },
  {
    id: 'almonds',
    category: 'dry_fruits',
    name: { en: 'Almonds', es: 'Almendras', ar: 'لوز', hi: 'बादाम', zh: '杏仁（扁桃仁）' },
    description: { en: 'Sweet, uniform unshelled California almonds, supreme grade.', es: 'Almendras dulces sin cáscara de calibre calibrado e impecables.', ar: 'لوز حلو مقشر متناسق الحجم بجريات عالية الدسامة.', hi: 'कैलिफोर्निया बादाम, समान आकार और श्रेष्ठ गुणवत्तायुक्त सुखाया हुआ।', zh: '加州优等脱壳原颗扁桃仁，无干缩，色泽红亮。' },
    image: resolveAsset('/assets/images/Almond.jpg'),
    details: {
      en: { origin: 'USA / India Processing', packaging: '25lb Kraft Boxes', moq: '20 MT', grade: 'Nonpareil Supreme 22/24', loadingCapacity: '20 MT per 20ft' },
      es: { origin: 'EE. UU. / India', packaging: 'Cajas de carton 25lb', moq: '20 MT', grade: 'Nonpareil 22/24 Supreme', loadingCapacity: '20 MT por 20 pies' },
      ar: { origin: 'أمريكا / تعبئة الهند', packaging: 'كراتين ورق ٢٥ رطل', moq: '٢٠ طن', grade: 'نونباريل ٢٢/٢٤ ممتاز', loadingCapacity: '٢٠ طن لكل ٢٠ قدم' },
      hi: { origin: 'यूएसए / भारत प्रोसेसिंग', packaging: '२५ पाउंड कार्टन बॉक्स', moq: '२० मीट्रिक टन', grade: 'नॉनपेरिल सुप्रीम २२/२४', loadingCapacity: '२० मीट्रिक टन प्रति २० फीट' },
      zh: { origin: '美国/印度加工', packaging: '25磅环保木色硬纸箱', moq: '20公吨', grade: 'Nonpareil 22/24 优级规格', loadingCapacity: '20公吨每20尺集装箱' }
    },
    specifications: {
      en: ['Size: 22/24 count/oz', 'Moisture: < 6%', 'Sound kernels: Min 99%'],
      es: ['Tamaño: 22/24 por oz', 'Humedad: < 6%', 'Granos Sanos: Mín 99%'],
      ar: ['المقاس: ٢٢/٢٤ في الأونصة', 'الرطوبة: < ٦٪', 'الحبات النظيفة: ٩٩٪ كحد أدنى'],
      hi: ['आकार: २२/२४ प्रति औंस', 'नमी: < ६%', 'स्वस्थ बादाम: न्यूनतम ९९%'],
      zh: ['粒重：每盎司22-24颗', '水分：低于6%', '良果率：不低于99%']
    }
  },
  {
    id: 'pistachios',
    category: 'dry_fruits',
    name: { en: 'Pistachios', es: 'Pistachos', ar: 'فستق', hi: 'पिस्ता', zh: '开心果' },
    description: { en: 'Gently salted, dry-roasted, sun-opened jumbo pistachios.', es: 'Pistachos jumbo de apertura natural medianamente salados y tostados.', ar: 'فستق حلبي محمص ومملح خفيف طبيعي الفتح.', hi: 'प्राकृतिक रूप से खिले और नमक लगाकर भुने स्वादिष्ट नमकीन पिस्ता।', zh: '自然熟成开口的特大原皮开心果，淡淡焙盐，香脆满口。' },
    image: pistachioImg,
    details: {
      en: { origin: 'USA / Iran', packaging: '25kg Bags', moq: '15 MT', grade: 'Jumbo Bold 20/22', loadingCapacity: '15 MT per 20ft' },
      es: { origin: 'EE. UU. / Irán', packaging: 'Sacos de 25kg', moq: '15 MT', grade: 'Bold Jumbo 20/22', loadingCapacity: '15 MT por 20 pies' },
      ar: { origin: 'أمريكا / إيران', packaging: 'أكياس خيش ٢٥ كجم', moq: '١٥ طن', grade: 'جامبو عريض ٢٠/٢٢', loadingCapacity: '١٥ طن لكل ٢٠ قدم' },
      hi: { origin: 'यूएसए / ईरान', packaging: '२५ किग्रा बैग', moq: '१५ मीट्रिक टन', grade: 'जंबो बोल्ड २०/२२', loadingCapacity: '१५ मीट्रिक टन प्रति २० फीट' },
      zh: { origin: '美国/伊朗', packaging: '25公斤加厚防护袋', moq: '15公吨', grade: 'Jumbo 特大级号 20/22', loadingCapacity: '15公吨每20尺集装箱' }
    },
    specifications: {
      en: ['Natural Shell Open: 95%+', 'Moisture: < 5%', 'Style: Salted & Roasted'],
      es: ['Apertura natural: 95%+', 'Humedad: < 5%', 'Esquema: Tostado y Salado'],
      ar: ['الفتح الطبيعي: ٩٥٪+', 'الرطوبة: < ٥٪', 'النكهة: محمص ومملح'],
      hi: ['प्राकृतिक खुला छिलका: ९५%+', 'नमी: < ५%', 'स्वाद: नमकीन व भुना'],
      zh: ['开心果物理开口率：不低于95%', '水分：低于5%', '产品工艺：盐焗低温烘制']
    }
  },
  {
    id: 'apples',
    category: 'fresh_produce',
    name: { en: 'Apples', es: 'Manzanas', ar: 'تفاح', hi: 'सेब', zh: '苹果' },
    description: { en: 'Fresh, sweet, and crisp premium red apples, direct from orchards.', es: 'Manzanas rojas frescas, dulces y crujientes, directamente de los huertos.', ar: 'تفاح أحمر طازج وحلو ومقرمش من البساتين مباشرة.', hi: 'ताजा, मीठा और कुरकुरा प्रीमियम लाल सेब, सीधे बगीचों से।', zh: '新鲜、鲜甜、爽脆的优质红苹果，果园直供。' },
    image: resolveAsset('/assets/images/apple.jpg'),
    details: {
      en: { origin: 'Himachal, India', packaging: '18kg Cartons', moq: '15 MT', grade: 'Royal Delicious Class I', loadingCapacity: '20 MT per 40ft Reefer' },
      es: { origin: 'Himachal, India', packaging: 'Cartones de 18kg', moq: '15 MT', grade: 'Royal Delicious Clase I', loadingCapacity: '20 MT por Reefer de 40 pies' },
      ar: { origin: 'هيماتشال، الهند', packaging: 'كراتين ١٨ كجم', moq: '١٥ طن', grade: 'رويال ديلشس فئة أولى', loadingCapacity: '٢٠ طن لكل ٤٠ قدم مبرد' },
      hi: { origin: 'हिमाचल, भारत', packaging: '१८ किग्रा कार्टन', moq: '१५ मीट्रिक टन', grade: 'रॉयल डेलिशियस क्लास I', loadingCapacity: '२० मीट्रिक टन प्रति ४० फीट रीफर' },
      zh: { origin: '喜马偕尔邦, 印度', packaging: '18公斤精装纸箱', moq: '15公吨', grade: '红星级 Royal Delicious 一级', loadingCapacity: '20公吨每40尺冷藏集装箱' }
    },
    specifications: {
      en: ['Fruit size: 75-85mm', 'Brix: 12-14%', 'Color: > 80% Blush'],
      es: ['Calibre: 75-85mm', 'Brix: 12-14%', 'Color: > 80% Rojo Intenso'],
      ar: ['حجم الثمرة: ٧٥-٨٥ ملم', 'نسبة السكر: ١٢-١٤٪', 'اللون: > ٨٠٪ احمرار ناصع'],
      hi: ['फल का आकार: ७५-८५ मिमी', 'ब्रिक्स: १२-१४%', 'रंग: > ८०% लालिमा'],
      zh: ['果径大小：75至85毫米', '糖度（Brix）：12%至14%', '上色率：不低于80%']
    }
  },
  {
    id: 'tomatoes',
    category: 'fresh_produce',
    name: { en: 'Tomatoes', es: 'Tomates', ar: 'طماطم', hi: 'टमाटर', zh: '番茄' },
    description: { en: 'Firm, plump red Roma tomatoes, picked at vine-ripe stage for long shelf life.', es: 'Tomates Roma firmes y carnosos, cosechados maduros para una larga vida útil.', ar: 'طماطم روما الحمراء المتماسكة والمليئة بالعصير，تقطف عند النضج لإطالة مدة الصلاحية.', hi: 'मजूद, गोल लाल रोमा टमाटर, लंबी शेल्फ लाइफ के लिए बेल पर पकने की अवस्था में चुने गए।', zh: '质地紧实、饱满圆润的红色罗马番茄，熟成期采摘以保证超长保鲜。' },
    image: tomatoImg,
    details: {
      en: { origin: 'Karnataka, India', packaging: '10kg Plastic Crates', moq: '12 MT', grade: 'Class I Vine-Ripe', loadingCapacity: '15 MT per 40ft Reefer' },
      es: { origin: 'Karnataka, India', packaging: 'Cajas plásticas de 10kg', moq: '12 MT', grade: 'Clase I Maduro de mata', loadingCapacity: '15 MT por Reefer de 40 pies' },
      ar: { origin: 'كارناتاكا، الهند', packaging: 'صناديق بلاستيكية ١٠ كجم', moq: '١٢ طن', grade: 'طماطم ناضجة على الأم فئة أولى', loadingCapacity: '١٥ طن لكل ٤٠ قدم مبرد' },
      hi: { origin: 'कर्नाटक, भारत', packaging: '१० किग्रा प्लास्टिक क्रेट', moq: '१२ मीट्रिक टन', grade: 'क्लास I बेल पर पका हुआ', loadingCapacity: '१५ मीट्रिक टन प्रति ४० फीट रीफर' },
      zh: { origin: '卡纳塔克邦, 印度', packaging: '10公斤网孔塑料筐', moq: '12公吨', grade: '一级熟透罗马番茄', loadingCapacity: '15公吨每40尺冷藏集装箱' }
    },
    specifications: {
      en: ['Calibration: 55-65mm', 'Color stage: Red (Stage 5)', 'Defective fruits: < 1%'],
      es: ['Calibre: 55-65mm', 'Nivel de color: Rojo (Fase 5)', 'Mermas: < 1%'],
      ar: ['المقاس: ٥٥-٦٥ ملم', 'مستوى اللون: أحمر ناصع (المرحلة ٥)', 'الثمار المعيبة: أقل من ١٪'],
      hi: ['आकार: ٥٥-٦٥ मिमी', 'रंग चरण: लाल (चरण ٥)', 'दोषपूर्ण फल: १% से कम'],
      zh: ['果径校准：55至65毫米', '颜色成熟度：红色（第5阶段）', '残次果率：少于1%']
    }
  },
  {
    id: 'corn',
    category: 'fresh_produce',
    name: { en: 'Sweet Corn', es: 'Maíz Dulce', ar: 'ذرة حلوة', hi: 'स्वीट कॉर्न', zh: '甜玉米' },
    description: { en: 'Plump and juicy sweet corn ears, sun-ripened and naturally sweet.', es: 'Mazorcas de maíz dulce carnosas y jugosas, maduradas al sol.', ar: 'أكواز الذرة الحلوة الممتلئة والعصارية，نضجت تحت أشعة الشمس وحلوة طبيعيًا.', hi: 'भरे हुए और रसीले स्वीट कॉर्न भुट्टे, धूप में पके और प्राकृतिक रूप से मीठे।', zh: '饱满多汁的黄甜玉米，光照充足，自然清甜。' },
    image: resolveAsset('/assets/images/Corn.jpg'),
    details: {
      en: { origin: 'Punjab, India', packaging: '15kg Mesh Bags / Crates', moq: '15 MT', grade: 'Super Sweet Grade A', loadingCapacity: '16 MT per 40ft Reefer' },
      es: { origin: 'Punjab, India', packaging: 'Sacos de malla o cajas de 15kg', moq: '15 MT', grade: 'Súper Dulce Grado A', loadingCapacity: '16 MT por Reefer de 40 pies' },
      ar: { origin: 'بنجاب، الهند', packaging: 'أكياس خيش شبكية ١٥ كجم', moq: '١٥ طن', grade: 'ذرة حلوة جدًا درجة أولى', loadingCapacity: '١٦ طن لكل ٤٠ قدم مبرد' },
      hi: { origin: 'पंजाब, भारत', packaging: '१५ किग्रा मेश बैग / बक्से', moq: '१५ मीट्रिक टन', grade: 'सुपर स्वीट ग्रेड A', loadingCapacity: '१६ मीट्रिक टन प्रति ४० फीट रीफर' },
      zh: { origin: '旁遮普邦, 印度', packaging: '15公斤网眼透气袋/塑料筐', moq: '15公吨', grade: '超甜A级', loadingCapacity: '16公吨每40尺冷藏集装箱' }
    },
    specifications: {
      en: ['Sugar content: 15%+', 'Length: 18-22cm', 'Husk: Fresh green intact'],
      es: ['Contenido de azúcar: 15%+', 'Length: 18-22cm', 'Husk: Fresh green intact'],
      ar: ['مستوى السكر: ١٥٪+', 'الطول: ١٨-٢٢ سم', 'الغلاف الخارجي: أخضر طازج وسليم'],
      hi: ['शर्करा की मात्रा: १५%+', 'लंबाई: १८-२२ सेमी', 'छिलका: ताजा हरा और बरकरार'],
      zh: ['含糖量：不低于15%', '单穗长度：18至22厘米', '外苞叶：鲜绿完整包裹']
    }
  },
  {
    id: 'oranges',
    category: 'fresh_produce',
    name: { en: 'Oranges', es: 'Naranjas', ar: 'برتقال', hi: 'संतरा', zh: '橙子' },
    description: { en: 'Juicy, sweet Valencia oranges with thin skins and rich vitamin C.', es: 'Naranjas de Valencia jugosas y dulces, con piel fina y ricas en vitamina C.', ar: 'برتقال فالنسيا العصاري والحلو ذو قشرة رقيقة ومصدر غني بفيتامين سي.', hi: 'पतले छिलके और विटामिन सी से भरपूर, रसीले व मीठे वेलेंसिया संतरे।', zh: '多汁、甘甜的瓦伦西亚橙，皮薄肉厚，富含天然维生素C。' },
    image: resolveAsset('/assets/images/Orange.jpg'),
    details: {
      en: { origin: 'Nagpur, India', packaging: '15kg Telescopic Cartons', moq: '20 MT', grade: 'Valencia Grade I', loadingCapacity: '22 MT per 40ft Reefer' },
      es: { origin: 'Nagpur, India', packaging: 'Cajas telescópicas de 15kg', moq: '20 MT', grade: 'Valencia Grado I', loadingCapacity: '22 MT por Reefer de 40 pies' },
      ar: { origin: 'ناغبور，الهند', packaging: 'كراتين تلسكوبية ١٥ كجم', moq: '٢٠ طن', grade: 'برتقال فالنسيا فئة أولى', loadingCapacity: '٢٢ طن لكل ٤٠ قدم مبرد' },
      hi: { origin: 'नागपुर, भारत', packaging: '१५ किग्रा टेलीस्कोपिक कार्टन', moq: '२० मीट्रिक टन', grade: 'वेलेंसिया ग्रेड I', loadingCapacity: '२२ मीट्रिक टन प्रति ४० फीट रीफर' },
      zh: { origin: '纳格浦尔, 印度', packaging: '15公斤套入式高强度纸箱', moq: '20公吨', grade: '瓦伦西亚一级果', loadingCapacity: '22公吨每40尺冷藏集装箱' }
    },
    specifications: {
      en: ['Size: 64/72/80/88 count', 'Juice content: Min 45%', 'Acid ratio: 8-12'],
      es: ['Calibres: 64/72/80/88 unidades', 'Contenido de jugo: Mín 45%', 'Relación acidez: 8-12'],
      ar: ['العدد: ٦٤/٧٢/٨٠/٨٨ حبة', 'محتوى العصير: ٤٥٪ كحد أدنى', 'نسبة الحموضة: ٨-١٢'],
      hi: ['आकार: ६४/७२/८०/८८ काउंट', 'रस की मात्रा: न्यूनतम ४५%', 'अम्लता अनुपात: ८-१२'],
      zh: ['规格包装：64/72/80/88颗箱装', '出汁率：不低于45%', '糖酸比：8至12']
    }
  },
  {
    id: 'potatoes',
    category: 'fresh_produce',
    name: { en: 'Potatoes', es: 'Patatas', ar: 'بطاطस', hi: 'आलू', zh: '土豆' },
    description: { en: 'Premium quality yellow potatoes, smooth-skinned and perfect for versatile culinary use.', es: 'Patatas amarillas de calidad premium, con piel suave e ideales para múltiples usos culinarios.', ar: 'بطاطس صفراء عالية الجودة，ملساء القشرة ومثالية للاستخدامات الطهي المتنوعة.', hi: 'प्रीमियम गुणवत्ता वाले पीले आलू, चिकनी त्वचा वाले और बहुमुखी पाक उपयोग के लिए उत्तम।', zh: '高品质黄金黄皮土豆，表皮光滑，芽眼浅，适合各种烹饪。' },
    image: resolveAsset('/assets/images/Potato.jpg'),
    details: {
      en: { origin: 'Gujarat, India', packaging: '50kg Mesh Bags', moq: '25 MT', grade: 'Grade A Multi-purpose', loadingCapacity: '26 MT per 40ft Reefer' },
      es: { origin: 'Gujarat, India', packaging: 'Sacos de malla de 50kg', moq: '25 MT', grade: 'Multiuso Grado A', loadingCapacity: '26 MT por Reefer de 40 pies' },
      ar: { origin: 'غوجارات، الهند', packaging: 'أكياس شبكية ٥٠ كجم', moq: '٢٥ طن', grade: 'بطاطس صالحة لكافة الاستخدامات فئة أ', loadingCapacity: '٢٦ طن لكل ٤٠ قدم مبرد' },
      hi: { origin: 'गुजरात, भारत', packaging: '५० किग्रा मेश बैग', moq: '२५ मीट्रिक टन', grade: 'ग्रेड A बहुउद्देशीय', loadingCapacity: '२६ मीट्रिक टन प्रति ४0 फीट रीफर' },
      zh: { origin: '古集拉特邦, 印度', packaging: '50公斤透气编织网眼袋', moq: '25公吨', grade: 'A级多用途级', loadingCapacity: '26公吨每40尺冷藏集装箱' }
    },
    specifications: {
      en: ['Size: 45mm+', 'Dry matter: 18-21%', 'Defects/Damage: < 1.5%'],
      es: ['Tamaño: 45mm+', 'Materia seca: 18-21%', 'Defectos/Daños: < 1.5%'],
      ar: ['المقاس: ٤٥ ملم فأكثر', 'المادة الجافة: ١٨-٢١٪', 'العيوب أو الكسور: أقل من ١.٥٪'],
      hi: ['आकार: ४५ मिमी+', 'ठोस पदार्थ: १८-२१%', 'खराबी/क्षति: १.५% से कम'],
      zh: ['规格：45毫米以上', '干物质含量：18%至21%', '慢/损伤率：少于1.5%']
    }
  },
  {
    id: 'wheat',
    category: 'grains',
    name: { en: 'Wheat', es: 'Trigo', ar: 'Trigo', hi: 'गेहूं', zh: '小麦' },
    description: { en: 'Golden premium Sharbati wheat, high in gluten and excellent for flour milling.', es: 'Trigo dorado premium Sharbati, de alto contenido en gluten y excelente molienda.', ar: 'قمح شارباتي الذهبي الممتاز，ذو محتوى بروتين عالي وممتاز للمطاحน وصنع الخبز.', hi: 'सुनहरा प्रीमियम शरबती गेहूं, उच्च ग्लूटेन और आटा मिलिंग के लिए उत्कृष्ट।', zh: '金黄色的优质莎尔巴蒂（Sharbati）小麦，高筋质，极其适合磨粉制面。' },
    image: resolveAsset('/assets/images/Wheat.jpg'),
    details: {
      en: { origin: 'Madhya Pradesh, India', packaging: '50kg Jute Bags', moq: '25 MT', grade: 'Premium Sharbati Grade I', loadingCapacity: '25 MT per 20ft' },
      es: { origin: 'Madhya Pradesh, India', packaging: 'Sacos de yute de 50kg', moq: '25 MT', grade: 'Premium Sharbati Grado I', loadingCapacity: '25 MT por 20 pies' },
      ar: { origin: 'ماديا براديش，الهند', packaging: 'أكياس خيش ٥٠ كجم', moq: '٢٥ طن', grade: 'قمح شاربات持续 ممتاز فئة أولى', loadingCapacity: '٢٥ طن لكل ٢٠ قدم' },
      hi: { origin: 'मध्य प्रदेश, भारत', packaging: '५० किग्रा जूट बैग', moq: '२५ मीट्रिक टन', grade: 'प्रीमियम शरबती ग्रेड I', loadingCapacity: '२५ मीट्रिक टन प्रति २० फीट' },
      zh: { origin: '马德里亚邦, 印度', packaging: '50公斤耐磨麻袋', moq: '25公吨', grade: '黄金 Sharbati 一级', loadingCapacity: '25公吨每20尺集装箱' }
    },
    specifications: {
      en: ['Protein content: 12-14%', 'Moisture: < 11%', 'Gluten wet: Min 28%'],
      es: ['Proteínas: 12-14%', 'Humedad: < 11%', 'Gluten húmedo: Mín 28%'],
      ar: ['نسبة البروتين: ١٢-١٤٪', 'الرطوبة: < ١١٪', 'الجلوتن الرطب: ٢٨٪ كحد أدنى'],
      hi: ['प्रोटीन की मात्रा: १२-१४%', 'नमी: < ११%', 'गीला ग्लूटेन: न्यूनतम २८%'],
      zh: ['蛋白质含量：12%至14%', '水分：低于11%', '湿面筋含量：不低于28%']
    }
  }
];

export const INITIAL_TRACKING_DATA: Record<string, Shipment> = {
  'ST-9283-IND': {
    trackingId: 'ST-9283-IND',
    commodity: {
      en: 'Organic Salem Turmeric Fingers',
      es: 'Cúrcuma en Rama Orgánica de Salem',
      ar: 'أصابع الكركم الهندية العضوية من نوع سالم',
      hi: 'जैविक सालेम हल्दी फिंगर गांठे',
      zh: '塞勒姆高纯姜黄干指'
    },
    vesselName: 'Setruck Wanderer',
    containerId: 'SEAU-883921-0',
    containerType: 'Reefer (20ft)',
    status: 'transit',
    originPort: { en: 'Mundra Port, India', es: 'Puerto de Mundra, India', ar: 'ميناء موندرا، الهند', hi: 'मुंद्रा बंदरगाह, भारत', zh: '印度蒙德拉港 (Mundra)' },
    destinationPort: { en: 'Jebel Ali, Dubai (UAE)', es: 'Jebel Ali, Dubái (EAU)', ar: 'جبل علي، دبي (الإمارات)', hi: 'जेबेल अली, दुबई (संयुक्त अरब अमीरात)', zh: '阿联酋杰贝阿里港 (Jebel Ali)' },
    departureDate: '2026-06-19',
    arrivalDate: '2026-06-23',
    temperature: '5.2 °C',
    humidity: '63%',
    currentLat: 22.8,
    currentLng: 62.1,
    milestones: [
      { status: 'processing', date: '2026-06-17', location: 'Ahmedabad Processing Facility, India', description: { en: 'Phytosanitary inspection complete and container sealed under cold environment.', es: 'Inspección fitosanitaria completada y contenedor sellado herméticamente.', ar: 'اكتملت الفحوصات الصحية وفحص الآفات الزراعية وتم إغلاق الحاوية في بيئة مبردة.', hi: 'फाइटोसेनेटरी निरीक्षण पूरा हुआ और प्रशीतित कोल्ड वातावरण में सील लगा दी गई।', zh: '植物检疫通关。进出口检疫审结并进行低温加封。' }, completed: true },
      { status: 'customs', date: '2026-06-18', location: 'Customs Yard Mundra, India', description: { en: 'Customs documents cleared. Certificate of Origin filed.', es: 'Documentos aduaneros aprobados. Certificado de origen emitido y validado.', ar: 'تم إنهاء وتخليص الأوراق الجمركية والشهادات وتفعيل شهادة المنشأ.', hi: 'सीमा शुल्क व कस्टम्स दस्तावेज स्वीकृत। उत्पत्ति का प्रमाणपत्र दर्ज किया गया।', zh: '海关核单报验。签发原产地证明以及国际贸易凭单。' }, completed: true },
      { status: 'loaded', date: '2026-06-19', location: 'Container Terminal Mundra, India', description: { en: 'Loaded onto vessel Setruck Wanderer. Reefer temperature powered.', es: 'Cargado de forma segura a bordo del Setruck Wanderer. Alimentación del contenedor refrigerado activada.', ar: 'تم التحميل على متن السفينة الاستيرادية سي ترك واندرر وتنشيط طاقة التبريد بنجاح.', hi: 'मरीन जहाज सीट्रक वांडरर पर कंटेनर चढ़ाया गया। रीफर पावर चालू कर दी गई।', zh: '安全装载至“Setruck Wanderer”巨型集装箱班轮，外接智能冷链温控电源并设定目标控制点。' }, completed: true },
      { status: 'transit', date: '2026-06-20', location: 'Arabian Sea (In Transit)', description: { en: 'Vessel cruising at average speed 18.5 knots. Temp controlled container powered and monitored via satellite.', es: 'Buque navegando a velocidad crucero de 18.5 nudos. Contenedor de temperatura controlado mediante satélite satelital.', ar: 'السفينة تبحر في البحر العربي بسرعة متوسطة ١٨.٥ عقدة. يتم تتبع الحاوية ومراقبة درجة الحرارة عن بعد عن طريق الأقمار الصناعية.', hi: '१८.५ समुद्री मील की औसत गति से जहाज आगे बढ़ रहा है। उपग्रह (Satellite) ट्रैकिंग द्वारा कंटेनर के तापमान की लाइव निगरानी जारी है।', zh: '国际干线快航以18.5节航速高速平稳行驶。在卫星传感器的支持下持续向岸站云后台推送高精度温湿度数据。' }, completed: true },
      { status: 'discharging', date: '2026-06-23', location: 'Jebel Ali Terminal 2, Dubai', description: { en: 'Shipment scheduled to arrive at berth. Handover ready for customs.', es: 'Llegada programada del buque al muelle. Listo para el traspaso de control en puerto.', ar: 'من المقرر وصول الشحنة إلى الرصيف المخصص لتفريغ الحمولة وتسليمها الجمركي.', hi: 'शिपमेंट के बंदरगाह बर्थ पर पहुंचने का समय निर्धारित। कस्टम विभाग को हैंडओवर की तैयारी।', zh: '预计靠泊时间。系统就绪卸船交付报关行并对接目的地口岸进口通关。' }, completed: false },
      { status: 'delivered', date: '2026-06-24', location: 'Consignee Warehouse Jebel Ali', description: { en: 'Final door delivery and unsealing after local phytosanitary checks.', es: 'Entrega final a pie de almacén y apertura del sello protector después de controles locales de sanidad.', ar: 'التسليم الإقليمي النهائي للمستودعات وفتح ختم الحاوية بعد فحص السلامة.', hi: 'स्थानीय फाइटोसेनेटरी जांच के बाद अंतिम गोदाम डिलीवरी और प्रशीतित द्वार अनसीलिंग।', zh: '完成目的地清关后极速陆运门到门配送，双重消毒后解除进口集装箱物理铅封，安心交付。' }, completed: false }
    ]
  },
  'ST-4821-NLD': {
    trackingId: 'ST-4821-NLD',
    commodity: {
      en: 'Premium long-grain Basmati Rice 1121',
      es: 'Arroz Basmati Premium de Grano Largo 1121',
      ar: 'أرز بسمتي هندي تقليدي فاخر عالي الطول ١١٢١',
      hi: 'प्रीमियम लंबे बासमती चावल ११२१',
      zh: '极品1121长粒巴斯马蒂香米'
    },
    vesselName: 'Setruck Sovereign',
    containerId: 'SEAU-110293-8',
    containerType: 'Dry FCL (40ft)',
    status: 'delivered',
    originPort: { en: 'Mundra Port, India', es: 'Puerto de Mundra, India', ar: 'ميناء موندرا، الهند', hi: 'मुंद्रा बंदरगाह, भारत', zh: '印度蒙德拉港 (Mundra)' },
    destinationPort: { en: 'Port of Rotterdam, Netherlands', es: 'Puerto de Rotterdam, Países Bajos', ar: 'ميناء روتردام، هولندا', hi: 'रॉटरडैम बंदरगाह, नीदरलैंड', zh: '荷兰鹿特丹港 (Rotterdam)' },
    departureDate: '2026-06-02',
    arrivalDate: '2026-06-20',
    temperature: 'Ambient Temp',
    humidity: '55%',
    currentLat: 51.9,
    currentLng: 4.1,
    milestones: [
      { status: 'processing', date: '2026-05-30', location: 'Mundra Silos, India', description: { en: 'Milling, Sortex cleaning, and double polish packing finished.', es: 'Fresado, limpieza Sortex y envasado pulido doble completado.', ar: 'تم تفريز وغسل وتجهيز الأرز وصقله بشكل مزدوج وتعبئته.', hi: 'अनाज की मिलिंग, सॉर्टेक्स सफाई और डबल पॉलिश डिब्बों में पैकिंग संपन्न।', zh: '大米碾米、除杂、高精度色选抛光 and 两层抗湿织袋高压自动封装。' }, completed: true },
      { status: 'customs', date: '2026-06-01', location: 'Mundra Port customs, India', description: { en: 'SGS quality testing verification complete and cleared.', es: 'Verificación y pruebas de calidad de la certificadora internacional SGS superadas.', ar: 'اكتمل فحص الجودة ومطابقة المواصفات من شركة الفحص العالمية SGS وتم تخليصه جمركياً.', hi: 'वैश्विक एजेंसी एसजीएस (SGS) द्वारा गुणवत्ता अनुमोदन। सीमा शुल्क मंजूरी प्राप्त।', zh: 'SGS国际权威第三方质检出具分析证书，水分、农残等关键指标完美达标并审结通关。' }, completed: true },
      { status: 'loaded', date: '2026-06-02', location: 'Mundra Port Terminal, India', description: { en: 'Ocean container loaded and secured aboard Setruck Sovereign container cargo vessel.', es: 'Contenedor marítimo cargado e inmovilizado a bordo del buque de carga Setruck Sovereign.', ar: 'تم تحميل وتثبيت الحاوية البحرية بنجاح على متن سفينة الشحن العملاقة سي ترك سوفرين.', hi: 'महासागरीय कंटेनर जहाज सीट्रक सॉवरेन पर सफलतापूर्वक कंटेनर लोड किया गया।', zh: '集装箱起吊，定位固定锁闭安装于大型吃水集装箱海轮“Setruck Sovereign”号。' }, completed: true },
      { status: 'transit', date: '2026-06-08', location: 'Red Sea / Suez Canal (Transit)', description: { en: 'Vessel scheduled transit through Suez Canal. Voyage tracking coordinates normal.', es: 'Buque navegando y transitando normalmente en el Canal de Suez. Coordenadas de posicionamiento satelital correctas.', ar: 'السفينة تبحر وتمر بسلام عبر قناة السويس في البحر الأحمر بوضع إبحار اعتيادي ومستقر.', hi: 'लाल सागर और प्रसिद्ध स्वेज नहर मार्ग से जहाज आगे बढ़ रहा है। समुद्री मापदंड पूरी तरह सामान्य।', zh: '船舶顺利越过曼德海峡，穿过红海、通过苏伊士运河。主辅机热工和压载水参数监控全部正常。' }, completed: true },
      { status: 'discharging', date: '2026-06-19', location: 'Rotterdam ECT Premium Gateway', description: { en: 'Vessel arrived at berth. Containers discharged from vessel using automated cranes.', es: 'Buque atracado en puerto. Contenedores descargados utilizando grúas pórtico automatizadas de alta capacidad.', ar: 'وصلت السفينة للرصيف. تم تفريغ الحاويات بنجاح باستخدام الرافعات القنطرية المؤتمتة.', hi: 'जहाज रॉटरडैम बंदरगाह पर पहुंचा। स्वचालित क्रेन द्वारा कंटेनर समुद्र तट पर उतारे गए।', zh: '船舶靠泊鹿特丹自动化干线港码头。重箱由电脑高架桥吊卸载进入海关堆场待申报。' }, completed: true },
      { status: 'delivered', date: '2026-06-20', location: 'Consignee Warehouse Amsterdam', description: { en: 'Door stepped customized logistics delivered to Amsterdam import partners. Clean receipt received.', es: 'Entrega logística final en almacén del cliente en Ámsterdam. Recepción limpia y conforme aprobada.', ar: 'تم التسليم والوصول لمستودعات الشركاء في أمستردام وأخذ توقيع إشعار الاستلام من الشركاء.', hi: 'एम्स्टर्डम आयातक भागीदार को अंतिम द्वार डिलीवरी पूरी हुई। शिपमेंट की बिना टूट-फूट साफ रसीद प्राप्त。', zh: '专线卡车集卡完成最终内陆配送，精准卸货至阿姆储丹进口采购商供应链大库，开箱验收确认无损签收。' }, completed: true }
    ]
  }
};

export const PORTS: Record<string, {
  id: string;
  name: string;
  country: { en: string; es: string; ar: string; hi: string; zh: string; };
  coords: { x: number; y: number; };
}> = {
  mundra: {
    id: 'mundra',
    name: 'Mundra Port',
    country: { en: 'India', es: 'India', ar: 'الهند', hi: 'भारत', zh: '印度' },
    coords: { x: 50, y: 35 }
  },
  shanghai: {
    id: 'shanghai',
    name: 'Shanghai Port',
    country: { en: 'China', es: 'China', ar: 'الصين', hi: 'चीन', zh: '中国' },
    coords: { x: 68, y: 28 }
  },
  singapore: {
    id: 'singapore',
    name: 'Port of Singapore',
    country: { en: 'Singapore', es: 'Singapur', ar: 'سنغافورة', hi: 'सिंगापुर', zh: '新加坡' },
    coords: { x: 62, y: 48 }
  },
  jebel_ali: {
    id: 'jebel_ali',
    name: 'Jebel Ali Port',
    country: { en: 'UAE', es: 'EAU', ar: 'الإمارات', hi: 'संयुक्त अरब अमीरात', zh: '阿联酋' },
    coords: { x: 42, y: 35 }
  },
  rotterdam: {
    id: 'rotterdam',
    name: 'Port of Rotterdam',
    country: { en: 'Netherlands', es: 'Países Bajos', ar: 'هولندا', hi: 'नीदरलैंड', zh: '荷兰' },
    coords: { x: 26, y: 15 }
  },
  mombasa: {
    id: 'mombasa',
    name: 'Port of Mombasa',
    country: { en: 'Kenya', es: 'Kenia', ar: 'كينيا', hi: 'केन्या', zh: '肯尼亚' },
    coords: { x: 34, y: 56 }
  }
};

export const ROUTES: Array<{
  id: string;
  origin: string;
  destination: string;
  vesselName: string;
  cargo: { en: string; es: string; ar: string; hi: string; zh: string; };
  transitDays: number;
}> = [
  {
    id: 'route-1',
    origin: 'mundra',
    destination: 'jebel_ali',
    vesselName: 'Setruck Wanderer',
    cargo: {
      en: 'Organic Turmeric & Fresh Spices',
      es: 'Cúrcuma Orgánica y Especias Frescas',
      ar: 'الكركم العضوي والتوابل الطازجة',
      hi: 'जैविक हल्दी और ताजे मसाले',
      zh: '有机姜黄和新鲜香料'
    },
    transitDays: 4
  },
  {
    id: 'route-2',
    origin: 'mundra',
    destination: 'rotterdam',
    vesselName: 'Setruck Sovereign',
    cargo: {
      en: 'Premium Basmati Rice 1121',
      es: 'Arroz Basmati Premium 1121',
      ar: 'أرز بسمتي هندي فاخر ١١٢١',
      hi: 'प्रीमियम बासमती चावल ११२१',
      zh: '特级 1121 巴斯马蒂香米'
    },
    transitDays: 18
  },
  {
    id: 'route-3',
    origin: 'singapore',
    destination: 'mombasa',
    vesselName: 'Setruck Titan',
    cargo: {
      en: 'Dry Fruits & Quality Grains',
      es: 'Frutos Secos y Granos de Calidad',
      ar: 'الفواكه المجففة والحبوب عالية الجودة',
      hi: 'सूखे मेवे और गुणवत्तापूर्ण अनाज',
      zh: '高档坚果和优质谷物'
    },
    transitDays: 12
  }
];

